version: '3.5'
services:
  mqtt:
    image: erlio/docker-vernemq
    ports:
      - 1883:1883
      - 9001:8080
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=iot-bmw-cloud
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata01:
    driver: local
