version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    ports:
      - 8081:8080
    networks:
    - proxynet
  mqtt:
    image: erlio/docker-vernemq:1.6.2
    ports:
      - 1883:1883
      - 9001:8080
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
    networks:
    - proxynet
  chunk-service:
    user: "node"
    build:
      context: .
      dockerfile: ChunkServiceDockerfile
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - MQTT=mqtt
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    networks:
    - proxynet
  coordinate-service:
    user: "node"
    build:
      context: .
      dockerfile: CoordinateServiceDockerfile
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - MQTT=mqtt
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    networks:
    - proxynet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=iot-bmw-cloud
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
    - proxynet
networks:
  proxynet:
    external:
      name: custom_network
volumes:
  esdata01:
    driver: local
